# Generated by Django 4.2.7 on 2023-11-19 14:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="WodMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repetitions",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wods.movement"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WodRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repetitions",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "movements",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wods.wodmovement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AMRAP", "Amrap"),
                            ("For Time", "For Time"),
                            ("Not For Time", "Not For Time"),
                            ("For Load", "For Load"),
                            ("EMOM", "Emom"),
                            ("TABATA", "Tabata"),
                        ]
                    ),
                ),
                (
                    "rounds",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wods.wodround"
                    ),
                ),
            ],
        ),
    ]
