# Generated by Django 4.2.7 on 2023-11-24 14:27

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MovementInRound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "repetitions",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wods.movement"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movements",
                    models.ManyToManyField(
                        through="wods.MovementInRound", to="wods.movement"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoundInWod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "repetitions",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wods.round"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AMRAP", "Amrap"),
                            ("For Time", "For Time"),
                            ("Not For Time", "Not For Time"),
                            ("For Load", "For Load"),
                            ("EMOM", "Emom"),
                            ("TABATA", "Tabata"),
                        ]
                    ),
                ),
                (
                    "rounds",
                    models.ManyToManyField(through="wods.RoundInWod", to="wods.round"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="roundinwod",
            name="wod",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wods.wod"
            ),
        ),
        migrations.AddField(
            model_name="movementinround",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wods.round"
            ),
        ),
    ]
