# Generated by Django 4.2.7 on 2023-11-28 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wods", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wod",
            name="rounds",
        ),
        migrations.AddField(
            model_name="round",
            name="repetitions",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Number of times the round is repeated",
            ),
        ),
        migrations.AlterField(
            model_name="movementinround",
            name="repetitions",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Number of time the movement is repeated",
            ),
        ),
        migrations.DeleteModel(
            name="RoundInWod",
        ),
    ]
