# Generated by Django 4.2.7 on 2023-12-08 16:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wods", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wod",
            name="rounds",
        ),
        migrations.AddField(
            model_name="round",
            name="repetitions",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="wod",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="wods.wod"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="RoundInWod",
        ),
    ]
